<?php
$tm_debug_level = 3;
// names of forms held as an array. First position NOT used. I.E., zero, and contains the controller.
$formsarray = array();
$formsarray[0] = 'index.php';
$formsarray[1] = 'login.html';
$formsarray[2] = 'errdisplay.html';
$formsarray[3] = 'currquery.html';
$formsarray[4] = 'addchgroles.html';
$formsarray[5] = 'pwordchange.html';
$formsarray[6] = 'errmaint.html';
$formsarray[7] = 'listerrmess.html';
$formsarray[8] = 'listgrouproles.html';
$formsarray[9] = 'listallusers.html';
$formsarray[10] = 'listannivs.html';
$formsarray[11] = 'addchgannivs.html';
$formsarray[12] = 'listallappnts.html';
$formsarray[13] = 'listtasks.html';
$formsarray[14] = 'addchgtasks.html';
$formsarray[15] = 'usermaint.html';
$formsarray[16] = 'copytasks.php';
$formsarray[17] = 'toggcompl.html';
$formsarray[18] = 'othrusr.html';
$formsarray[19] = 'addchgappnts.html';
?>